/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubuh.ideal;

import javax.swing.JOptionPane;

/**
 *
 * @author Ridjal Fathoni
 */
public class frame1 extends javax.swing.JFrame {
    String temp;
    Double tinggi,berat,hasil;
    /**
     * Creates new form frame1
     */
    public frame1() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        p = new javax.swing.JRadioButton();
        hasil1 = new javax.swing.JTextField();
        l = new javax.swing.JRadioButton();
        hasil2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        hit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cob = new javax.swing.JButton();
        kel = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        bhasil = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        n = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        b = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        bg.add(p);
        p.setText("PEREMPUAN");
        getContentPane().add(p);
        p.setBounds(170, 160, 100, 23);

        hasil1.setEditable(false);
        getContentPane().add(hasil1);
        hasil1.setBounds(57, 288, 330, 30);

        bg.add(l);
        l.setText("LAKI LAKI");
        getContentPane().add(l);
        l.setBounds(270, 160, 110, 23);

        hasil2.setEditable(false);
        getContentPane().add(hasil2);
        hasil2.setBounds(57, 324, 330, 30);

        jLabel9.setText("cm");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(240, 90, 30, 14);

        hit.setText("HITUNG");
        hit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitActionPerformed(evt);
            }
        });
        getContentPane().add(hit);
        hit.setBounds(57, 201, 90, 23);

        jLabel10.setText("kg");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(240, 120, 30, 14);

        cob.setText("COBA LAGI");
        cob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobActionPerformed(evt);
            }
        });
        getContentPane().add(cob);
        cob.setBounds(180, 200, 110, 23);

        kel.setText("KELUAR");
        kel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelActionPerformed(evt);
            }
        });
        getContentPane().add(kel);
        kel.setBounds(320, 200, 80, 23);

        jLabel6.setText("BERAT BADAN IDEAL ANDA ADALAH");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(57, 245, 220, 14);
        getContentPane().add(bhasil);
        bhasil.setBounds(290, 230, 36, 30);

        jLabel7.setText("kg");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(340, 250, 40, 14);

        jLabel1.setText("CEK IDEAL TUBUH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(154, 11, 140, 14);

        jLabel2.setText("NAMA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(57, 49, 50, 14);

        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });
        getContentPane().add(n);
        n.setBounds(170, 40, 220, 30);

        jLabel3.setText("TINGGI");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(57, 87, 50, 14);

        t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tActionPerformed(evt);
            }
        });
        getContentPane().add(t);
        t.setBounds(170, 80, 38, 30);

        jLabel4.setText("BERAT BADAN");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(57, 125, 100, 14);

        jLabel5.setText("JENIS KELAMIN");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(57, 164, 90, 14);
        getContentPane().add(b);
        b.setBounds(170, 120, 38, 30);

        jLabel8.setText("HASIL DIAGNOSA KESEHATAN");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(127, 268, 180, 14);

        setSize(new java.awt.Dimension(429, 416));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitActionPerformed
        // TODO add your handling code here:
        if (n.getText().equals("")||t.getText().equals("")||b.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Data inputan harus diisi");
        }
        else if (p.isSelected()||l.isSelected())
        {
            try
            {
                Proses();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "Data inputan salah");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Jenis Kelamin belum dipilih");
        }
    }//GEN-LAST:event_hitActionPerformed

    private void cobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobActionPerformed
        // TODO add your handling code here:
        n.setText("");
        t.setText("");
        b.setText("");
        bg.clearSelection();
        bhasil.setText("");
        hasil1.setText("");
        hasil2.setText("");
        
    }//GEN-LAST:event_cobActionPerformed

    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nActionPerformed

    private void tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tActionPerformed

    private void kelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_kelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b;
    private javax.swing.ButtonGroup bg;
    private javax.swing.JTextField bhasil;
    private javax.swing.JButton cob;
    private javax.swing.JTextField hasil1;
    private javax.swing.JTextField hasil2;
    private javax.swing.JButton hit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton kel;
    private javax.swing.JRadioButton l;
    private javax.swing.JTextField n;
    private javax.swing.JRadioButton p;
    private javax.swing.JTextField t;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
        tinggi = Double.valueOf(t.getText());
        berat = Double.valueOf(b.getText());
        
        if(p.isSelected())
        {
            hasil = (tinggi - 104) * 1;
        }
        else if (l.isSelected())
        {
            hasil = (tinggi - 104) * 1;
        }
        temp = Double.toString(hasil.intValue());
    
    
    if(hasil<berat)
    {
        bhasil.setText(temp);
        hasil1.setText("Maaf " + n.getText() + ", Sepertinya anda Overheight :(");
        hasil2.setText("Banyaklah berolahraga dan hindari makanan berkolesterol");
    }
    else if (hasil > berat)
    {
        bhasil.setText(temp);
        hasil1.setText("Maaf " + n.getText() + ", Sepertinya anda Underheight :(");
        hasil2.setText("Banyaklah mengkonsumsi makanan berkarbohidrat");
    }
    else
    {
        bhasil.setText(temp);
        hasil1.setText("Hallo " + n.getText() + ", Berat badan anda sudah ideal :)");
        hasil2.setText("Lanjutkan");
    }
    }
 }

